kafka:
  brokers: "localhost:9092"
  topic: "ticket.creation"

postgres:
  host: "localhost"
  port: "5432"
  username: "satoro"
  password: "gojo"
  database: "ticket-system"

consul:
  consul_address: "localhost:8500"
  health_check_interval: "10s"
  health_check_timeout: "10s"