version: '3.8'

services:
  # Auth service
  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ./docker/auth/config/config.yaml:/config/config.yaml
      - ./docker/auth/config/clients.json:/hydra/clients.json
    networks:
      - my-net

  # User manager service
  user-manager:
    build:
      context: ./user-manager
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    volumes:
      - ./docker/user-manager/config:/config
    networks:
      - my-net

  ticket:
    build:
      context: ./ticket-service
      dockerfile: Dockerfile
    ports:
      - "8084:8080"
    volumes:
      - ./docker/ticket/config:/config
    networks:
      - my-net

  # Notification service
  notification-service:
    build:
      context: ./notification-service
      dockerfile: Dockerfile
    ports:
      - "8083:8080"
    volumes:
      - ./docker/notification/.env:/.env
    networks:
      - my-net

  # Gateway
  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    volumes:
      - ./docker/gateway/.env:/.env
    ports:
      - "81:81"
    depends_on:
      - auth-service
      - user-manager
      - notification-service
    networks:
      - my-net

networks:
  my-net:
    external: true