database:
  host: "localhost"
  port: "5432"
  username: "satoro"
  password: "gojo"
  database: "ticket-system"
  max_conns: 3

hydra:
  admin_url: "http://localhost:4445/admin"
  debug: false

server:
  address: ":8080"

grpc:
  address: ":8081"

hash:
  salt: "somesalt"
  cost: 10

kafka:
  brokers: "localhost:9092"
  topic: "new_users"
  group_id": "auth_service_1"