database:
  host: "db"
  port: "5432"
  username: "satoro"
  password: "gojo"
  database: "ticket-system"
  max_conns: 3

hydra:
  admin_url: "http://hydra:4445"
  debug: false

server:
  address: ":8080"

grpc:
  address: ":8081"

hash:
  salt: "somesalt"
  cost: 10

rabbit:
  host: "rabbitmq"
  port: 5672
  user: "admin"
  password: "password"
  queue: "new_users"
  pool_size: 3

consul:
  consul_address: "consul:8500"
  health_check_interval: "10s"
  health_check_timeout: "10s"